import * as collectedPlatformProviders from "../providers";
import * as common from "./common";

export const GenerateCommonPlatformResourcesCode = ( allPlatformProviders: ReadonlyArray<string> ) => `// This file was auto-generated by TS script!

${allPlatformProviders.reduce( ( prevString, provider ) => `${prevString}
import * as ${ provider} from "${common.GetPathFromProviderName( provider )}";`, "" )}

export const AllResources = {${ allPlatformProviders.reduce( ( prevString, provider ) => `${prevString}
  ...${provider}.AllResources`, "" )}
} as const;

export const AllDataSources = {${ allPlatformProviders.reduce( ( prevString, provider ) => `${prevString}
  ...${provider}.AllDataSources`, "" )}
} as const;
`

console.log( GenerateCommonPlatformResourcesCode( collectedPlatformProviders.allProviders ) );