export const GenerateTypeScript = ( allPlatformProviders: ReadonlyArray<string> ) => `// This file was auto-generated by TS script!

${allPlatformProviders.reduce( ( prevString, provider ) => `${prevString}
import * as ${ provider} from "${GetPathFromProviderName( provider )}";`, "" )}

export const AllResources = {${ allPlatformProviders.reduce( ( prevString, provider ) => `${prevString}
  ...${provider}.AllResources`, "" )}
} as const;

export const AllDataSources = {${ allPlatformProviders.reduce( ( prevString, provider ) => `${prevString}
  ...${provider}.AllDataSources`, "" )}
} as const;
`;

export const GenerateTSConfig = ( allPlatformProviders: ReadonlyArray<string> ) => ( {
  "extends": "../../../../../tsconfig.project.json",
  "include": [
    "./*.ts"
  ],
  "compilerOptions": {
    "composite": true,
    "outDir": "../../../../../ts_out"
  },
  "references": allPlatformProviders.map( ( provider ) => ( { "path": GetPathFromProviderName( provider ) } ) )
} );

const GetPathFromProviderName = ( provider: string ) => `../../../providers/${provider}/resources`;
