import * as collectedPlatformProviders from "../providers";
import * as common from "./common";

export const GenerateCommonPlatformResourcesCode = ( allPlatformProviders: ReadonlyArray<string> ) => `// This file was auto-generated by TS script!

${allPlatformProviders.reduce( ( prevString, provider ) => `${prevString}
import * as res_${ provider} from "${common.GetPathFromProviderName( provider, "/inputs" )}";
import * as data_${ provider} from "${common.GetPathFromProviderName( provider, "/inputs-data" )}";
`, "" )}

export const AllSchemas = {${ allPlatformProviders.reduce( ( prevString, provider ) => `${prevString}
  ...res_${provider}.AllSchemas`, "" )}
} as const;

export const AllDataSources = {${ allPlatformProviders.reduce( ( prevString, provider ) => `${prevString}
  ...data_${provider}.AllSchemas`, "" )}
} as const;
`

console.log( GenerateCommonPlatformResourcesCode( collectedPlatformProviders.allProviders ) );